### ISSUE TITLE
New maintainer needed

### ISSUE THREAD

**Issue by janunger** [janunger/aqbanking-php#10]
Anyone interested in taking over this lib? I don't use it anymore, so I'm kinda the wrong person to maintain it.

**Comment by amenk** [comment]
@janunger  Ich würd's nehmen .... Account: mestrona

**Comment by janunger** [comment]
@amenk Ich kann's nicht an mestrona übertragen, weil ich dazu Schreibrechte für die Organisation bräuchte. An amenk kann ich's nicht übertragen, weil's amenk/aqbanking-php schon gibt. Willst du einfach deinen fork auf packagist publishen und ich verweise drauf als successor? Danach würde ich dieses Repo hier archivieren.

**Comment by amenk** [comment]
I saw @mark-win did some modernization as well ... will email him

**Comment by amenk** [comment]
@janunger here we go: https://github.com/Mestrona/aqbanking-php https://packagist.org/packages/mestrona/aqbanking-php

**Comment by janunger** [comment]
Nice! Thanks for keeping it alive. 👍
