### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by chazdiezal** [janunger/aqbanking-php#2]
What file do I set the bank configs in?  Which file do I run in order to kick off this script?  I'm use to using it in gnucash but want to run aqbanking-php from command line.

**Comment by janunger** [comment]
This is an adapter library, not a fully implemented application. You need to have a surrounding piece of software that uses the commands in src/AqBanking/Command. For example, to check if AqBanking is reachable via this lib, have something like
```php
$command = new AqBanking\Command\CheckAqBankingCommand();
try {
    $command->execute();
} catch (Exception $e) {
    echo $e->getMessage();
    exit(1);
}
echo 'AqBanking version check successful';
exit(0);
```
